### ISSUE TITLE
Can not load symbol files to a debug session

### ISSUE THREAD

**Issue by Hermann-Core** [Marus/cortex-debug#864]
Hello. I'm trying to flash 2 binaries in my MCU using only the hex files and the load symbols for debug using the extracted symbols files from objcopy but it didn't work. It said that symbols are not recognized.
This is my launch.json file
```
{
        "name": "Debug",
        "request": "launch",
        "type": "cortex-debug",
        "cwd": "${workspaceFolder}",
        "executable": "${workspaceFolder}/bin/debug/bootloader.out",
        "loadFiles": [
          "${workspaceFolder}/bin/debug/bootloader.hex",
          "${workspaceFolder}/bin/debug/main_app.hex"
        ],
        "symbolFiles": [
          {"file": "${workspaceFolder}/bin/debug/bootloader.dbg"},
          {"file": "${workspaceFolder}/bin/debug/main_app.dbg"}
        ],
        "servertype": "jlink",
        "serverpath": "${env:ProgramFiles}/SEGGER/JLink/JLinkGDBServerCL.exe",
        "runToEntryPoint": "main",
        "device": "STM32F303VC",
        "liveWatch": {
          "enabled": true,
          "samplesPerSecond": 4
        },
        "showDevDebugOutput": "raw",
        "rttConfig": {
          "enabled": true,
          "address": "auto",
          "decoders": [
              {
                  "label": "",
                  "port": 0,
                  "type": "console",
                  "iencoding": "utf8",
              }
          ]
        },
        "preLaunchTask": "CMake: build",
        "svdPath": "${workspaceFolder}/device/SVD_file/STM32F303.svd"
      }
```
This is the output from Debug console
```
-> 5^done
6-interpreter-exec console "source c:/Users/herma/.vscode/extensions/marus25.cortex-debug-1.11.1/support/gdbsupport.init"
-> 6^done
7-interpreter-exec console "source c:/Users/herma/.vscode/extensions/marus25.cortex-debug-1.11.1/support/gdb-swo.init"
-> =cmd-param-changed,param="language",value="c"
-> =cmd-param-changed,param="language",value="auto"
-> 7^done
8-interpreter-exec console "set output-radix 0xa"
-> ~"Output radix now set to decimal 10, hex a, octal 12.\n"
Output radix now set to decimal 10, hex a, octal 12.
-> 8^done
9-interpreter-exec console "set input-radix 0xa"
-> ~"Input radix now set to decimal 10, hex a, octal 12.\n"
Input radix now set to decimal 10, hex a, octal 12.
-> 9^done
10-interpreter-exec console "add-symbol-file \"C:/Users/herma/Bureau/Hermann/EBIKE/Codes/Firmware/bin/debug/bootloader.dbg\""
-> ~"add symbol table from file \"C:/Users/herma/Bureau/Hermann/EBIKE/Codes/Firmware/bin/debug/bootloader.dbg\"\n"
add symbol table from file "C:/Users/herma/Bureau/Hermann/EBIKE/Codes/Firmware/bin/debug/bootloader.dbg"
-> ~"(y or n) [answered Y; input not from terminal]\n"
(y or n) [answered Y; input not from terminal]
-> &"`C:\\Users\\herma\\Bureau\\Hermann\\EBIKE\\Codes\\Firmware\\bin\\debug\\bootloader.dbg': can't read symbols: file format not recognized.\n"
`C:\Users\herma\Bureau\Hermann\EBIKE\Codes\Firmware\bin\debug\bootloader.dbg': can't read symbols: file format not recognized.
-> 10^error,msg="`C:\\Users\\herma\\Bureau\\Hermann\\EBIKE\\Codes\\Firmware\\bin\\debug\\bootloader.dbg': can't read symbols: file format not recognized."
11-interpreter-exec console "add-symbol-file \"C:/Users/herma/Bureau/Hermann/EBIKE/Codes/Firmware/bin/debug/main_app.dbg\""
Failed to generate gdb commands: `C:\Users\herma\Bureau\Hermann\EBIKE\Codes\Firmware\bin\debug\bootloader.dbg': can't read symbols: file format not recognized. (from interpreter-exec console "add-symbol-file \"C:/Users/herma/Bureau/Hermann/EBIKE/Codes/Firmware/bin/debug/bootloader.dbg\"")
`C:\Users\herma\Bureau\Hermann\EBIKE\Codes\Firmware\bin\debug\bootloader.dbg': can't read symbols: file format not recognized.
    at i (c:\Users\herma\.vscode\extensions\marus25.cortex-debug-1.11.1\dist\debugadapter.js:2:147816)
    at handlers.<computed> (c:\Users\herma\.vscode\extensions\marus25.cortex-debug-1.11.1\dist\debugadapter.js:2:148310)
    at c:\Users\herma\.vscode\extensions\marus25.cortex-debug-1.11.1\dist\debugadapter.js:2:135616
    at Array.forEach (<anonymous>)
    at b.onOutput (c:\Users\herma\.vscode\extensions\marus25.cortex-debug-1.11.1\dist\debugadapter.js:2:135045)
    at b.stdout (c:\Users\herma\.vscode\extensions\marus25.cortex-debug-1.11.1\dist\debugadapter.js:2:134462)
    at Socket.emit (node:events:526:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Readable.push (node:internal/streams/readable:228:10)
```
![image](https://user-images.githubusercontent.com/65020150/229530098-c060aa20-af27-42db-9f44-22c6206dbd53.png)

**Comment by haneefdm** [comment]
What are those symbol files? GDB does not understand them. They need to be ELF files created by a proper compiler/linker.

**Comment by Hermann-Core** [comment]
> What are those symbol files? GDB does not understand them. They need to be ELF files created by a proper compiler/linker.

```
herma@Hermann MINGW64 ~/Bureau/Hermann/EBIKE/Codes/Firmware/bin/debug (Dev)
$ tiarmobjcopy --only-keep-debug main_app.out main_app.dbg

herma@Hermann MINGW64 ~/Bureau/Hermann/EBIKE/Codes/Firmware/bin/debug (Dev)
$ tiarmobjcopy --only-keep-debug bootloader.out bootloader.elf

herma@Hermann MINGW64 ~/Bureau/Hermann/EBIKE/Codes/Firmware/bin/debug (Dev)
$ tiarmobjcopy --only-keep-debug main_app.out main_app.elf
```
I used theses commands to extract the debug symbols.

**Comment by Hermann-Core** [comment]
that was a misinterpretation sorry. I passed the direct elf files as symbolFiles and everything worked fine thank you. now I have 2 problems:
* I can't seem to flash the .bin files. I get an unrecognized file error instead
* The debugging is a bit slow and sometimes it crashes when reading a variable for example. I have some kind of loading icon on the `locale` watch option that doesn't stop. I have to end the debugging manually.

**Comment by haneefdm** [comment]
Try using hex/elf files instead. Maybe file format is not what gdb is expecting. It is between you and gdb. I really don't understand what you are trying to do. I am out of my depth and taking a lot of my time. Maybe someone else can help you. Please study every command sent to gdb and make sure it makes sense for your setup. Also, look at the gdb-server window. Also, have you tried stlink or openocd?

You can use the memory viewer to see if your device is properly programmed.

**Comment by Hermann-Core** [comment]
> Also, have you tried stlink or openocd?
I'm using jlink mainly for RTT and RTTViewer. I think it is also slight faster compared to OpenOCD and jlink
> You can use the memory viewer to see if your device is properly programmed.
Didn't aware of this feature. How to enable the memory view ?

**Comment by haneefdm** [comment]
https://github.com/mcu-debug/memview

You should also know all the commands/settings (FEATURE CONTRIBUTIONS) of Cortex-Debug or any extension. There are shown in the Extension manager

<img width="1100" alt="image" src="https://user-images.githubusercontent.com/41269583/229660135-4c560784-5475-4f73-8962-19ab8fdbcb46.png">

**Comment by Hermann-Core** [comment]
Thans for your attention. You can close the issue
